version: 1.4.3.{build}
image: Visual Studio 2017
skip_non_tags: false
configuration: Release
init:
- cmd: "if DEFINED APPVEYOR_REPO_TAG_NAME (set CUSTOM_BUILD_NUMBER=%APPVEYOR_REPO_TAG_NAME%) ELSE (set CUSTOM_BUILD_NUMBER=v%APPVEYOR_BUILD_VERSION%)"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
  - 7z a xslt-cli-%CUSTOM_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\xslt-cli\bin\%CONFIGURATION%\xslt-cli.ex*
artifacts:
  - path: xslt-cli-%CUSTOM_BUILD_NUMBER%.zip
deploy:
  release: $(appveyor_repo_tag_name)
  description: ''
  provider: GitHub
  auth_token:
    secure: 7T+aUcPgiRzaxvOIQOEzlgKfK/Ni3aOSI6XM/tahsOx87NRiZ1B0sHuIBJ0KYFUz
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
